spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_test
    username: postgres
    password: 4444
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
