DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
CREATE TABLE authors(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE genres(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE books(id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, author_id BIGINT,
                   genre_id BIGINT, FOREIGN KEY(author_id) REFERENCES authors(id) ON DELETE CASCADE
                       ON UPDATE CASCADE, FOREIGN KEY (genre_id) REFERENCES genres(id)
                       ON DELETE CASCADE ON UPDATE CASCADE );
CREATE TABLE comments(id BIGINT AUTO_INCREMENT PRIMARY KEY, book_id BIGINT, content VARCHAR(500),
                      FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE);